# Generated by Django 3.0.1 on 2019-12-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
