# Generated by Django 3.0.1 on 2020-01-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0002_auto_20191225_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('favourites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookhub.Textbook')),
            ],
        ),
    ]
