# Generated by Django 3.0.1 on 2020-01-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookhub', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recents',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recents', to='bookhub.Textbook'),
            preserve_default=False,
        ),
    ]
